#!/usr/bin/env python3
"""Sync @lectio/page contracts into backend committed snapshots.

Canonical source: packages/lectio-page (or LECTIO_PAGE_PACKAGE_DIR).
Idempotent: running twice must leave no diff on synced artifacts.
"""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path

SYNC_FILES = (
    "lectio-document-v2.schema.json",
    "intent-catalogue.v1.json",
    "object-catalogue.v1.json",
    "manifest.json",
)


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _repo_root() -> Path:
    # tools/ → textbook-agent/
    return Path(__file__).resolve().parent.parent


def _monorepo_root(repo_root: Path) -> Path:
    # apps/textbook-agent → monorepo root
    return repo_root.parent.parent


def _page_package_dir(repo_root: Path) -> Path:
    override = os.environ.get("LECTIO_PAGE_PACKAGE_DIR")
    if override:
        candidate = Path(override)
    else:
        candidate = _monorepo_root(repo_root) / "packages" / "lectio-page"
        if not candidate.exists():
            # Fallback: sibling layout during early bootstrap experiments
            candidate = repo_root / "packages" / "lectio-page"
    if not candidate.exists():
        raise FileNotFoundError(
            f"@lectio/page package not found at '{candidate}'. "
            "Set LECTIO_PAGE_PACKAGE_DIR or run from the monorepo."
        )
    return candidate


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def _sync_json_files(source_contracts: Path, target_dir: Path) -> dict[str, dict]:
    target_dir.mkdir(parents=True, exist_ok=True)
    file_meta: dict[str, dict] = {}
    for name in SYNC_FILES:
        source = source_contracts / name
        if not source.exists():
            raise FileNotFoundError(f"Missing page contract: {source}")
        target = target_dir / name
        payload = source.read_bytes()
        target.write_bytes(payload)
        file_meta[name] = {
            "path": name,
            "sha256": hashlib.sha256(payload).hexdigest(),
            "bytes": len(payload),
        }
    # Remove stale json not in sync set (keep sync-manifest.json)
    for stale in target_dir.glob("*.json"):
        if stale.name not in SYNC_FILES and stale.name != "sync-manifest.json":
            stale.unlink()
    return file_meta


def _load_catalogue_ids(path: Path, key: str) -> list[str]:
    data = json.loads(path.read_text(encoding="utf-8"))
    items = data.get(key, {})
    if isinstance(items, dict):
        return sorted(items.keys())
    if isinstance(items, list):
        return sorted(str(x) for x in items)
    raise ValueError(f"Unexpected catalogue shape in {path}")


def _generate_python_adapter(
    *,
    object_ids: list[str],
    intent_ids: list[str],
    catalogue_version: str,
    contract_version: str,
    file_meta: dict[str, dict],
) -> str:
    obj_literal = ", ".join(json.dumps(i) for i in object_ids)
    intent_literal = ", ".join(json.dumps(i) for i in intent_ids)
    hashes = {name: meta["sha256"] for name, meta in sorted(file_meta.items())}
    content_fingerprint = hashlib.sha256(
        json.dumps(hashes, sort_keys=True).encode("utf-8")
    ).hexdigest()[:12]
    return f'''# AUTO-GENERATED by tools/update_lectio_page_contracts.py
# Do not edit by hand. Re-run the sync script after catalogue/schema changes.
# Content fingerprint: {content_fingerprint}

from __future__ import annotations

from typing import Any, Literal

PAGE_OBJECT_IDS: tuple[str, ...] = ({obj_literal},)
INTENT_IDS: tuple[str, ...] = ({intent_literal},)

PageObjectId = Literal[{obj_literal}]
IntentId = Literal[{intent_literal}]

CATALOGUE_VERSION = {json.dumps(catalogue_version)}
CONTRACT_VERSION = {json.dumps(contract_version)}
SYNCED_FILE_HASHES: dict[str, str] = {json.dumps(hashes, indent=4)}

DocumentContractVersion = Literal[1, 2]


def is_known_object(object_id: str) -> bool:
    return object_id in PAGE_OBJECT_IDS


def is_known_intent(intent_id: str) -> bool:
    return intent_id in INTENT_IDS


def catalogue_snapshot() -> dict[str, Any]:
    return {{
        "catalogue_version": CATALOGUE_VERSION,
        "contract_version": CONTRACT_VERSION,
        "objects": list(PAGE_OBJECT_IDS),
        "intents": list(INTENT_IDS),
        "hashes": dict(SYNCED_FILE_HASHES),
    }}
'''


def main() -> int:
    repo_root = _repo_root()
    page_dir = _page_package_dir(repo_root)
    source_contracts = page_dir / "contracts"
    target_dir = repo_root / "backend" / "contracts" / "lectio-page"
    generated_path = repo_root / "backend" / "src" / "contracts" / "generated" / "lectio_page.py"

    file_meta = _sync_json_files(source_contracts, target_dir)

    object_cat = json.loads((target_dir / "object-catalogue.v1.json").read_text(encoding="utf-8"))
    intent_cat = json.loads((target_dir / "intent-catalogue.v1.json").read_text(encoding="utf-8"))
    package_manifest = json.loads((target_dir / "manifest.json").read_text(encoding="utf-8"))

    object_ids = _load_catalogue_ids(target_dir / "object-catalogue.v1.json", "objects")
    intent_ids = _load_catalogue_ids(target_dir / "intent-catalogue.v1.json", "intents")
    catalogue_version = str(object_cat.get("catalogue_version") or intent_cat.get("catalogue_version") or "")
    contract_version = str(package_manifest.get("contract_version") or "1.0.0")

    # Omit wall-clock timestamps so the sync is byte-idempotent.
    sync_manifest = {
        "sync_tool": "update_lectio_page_contracts.py",
        "source_package": "@lectio/page",
        "catalogue_version": catalogue_version,
        "contract_version": contract_version,
        "files": {name: file_meta[name] for name in SYNC_FILES},
    }
    _write_text(
        target_dir / "sync-manifest.json",
        json.dumps(sync_manifest, indent=2, ensure_ascii=False) + "\n",
    )

    adapter = _generate_python_adapter(
        object_ids=object_ids,
        intent_ids=intent_ids,
        catalogue_version=catalogue_version,
        contract_version=contract_version,
        file_meta=file_meta,
    )
    _write_text(generated_path, adapter)

    # Ensure package marker for generated module
    init_path = generated_path.parent / "__init__.py"
    if not init_path.exists():
        _write_text(init_path, '"""Generated Lectio contract adapters."""\n')

    print(f"Synced @lectio/page contracts from: {source_contracts}")
    print(f"  - target: {target_dir}")
    print(f"  - files: {len(file_meta)}")
    print(f"  - catalogue_version: {catalogue_version}")
    print(f"  - generated: {generated_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
