"""Path-neutral shared lesson artifact contract."""

from document.shared_lesson.composer import (
    CompositionChoice,
    CompositionItem,
    CompositionPolicy,
    CompositionValidationError,
    SectionCompositionDraft,
    SectionCompositionPlan,
    compose_section,
    validate_and_build_composition,
    validate_composition_plan,
)
from document.shared_lesson.hashing import (
    canonical_shared_lesson_payload,
    shared_lesson_content_hash,
    verify_shared_lesson_source,
)
from document.shared_lesson.models import (
    CalloutNode,
    FigureNode,
    HeadingNode,
    ListNode,
    ParagraphNode,
    SharedLessonDocument,
    SharedProvenance,
    SharedSection,
    TableNode,
    TaskAnchor,
    build_shared_lesson_document,
)
from document.shared_lesson.writer import (
    SectionSource,
    SectionTaskSummary,
    SectionWriteResult,
    SectionWriteValidationError,
    SectionWriterDraft,
    SectionWriterRequest,
    validate_and_build_section,
    write_section,
)

__all__ = [
    "CalloutNode",
    "CompositionChoice",
    "CompositionItem",
    "CompositionPolicy",
    "CompositionValidationError",
    "FigureNode",
    "HeadingNode",
    "ListNode",
    "ParagraphNode",
    "SharedLessonDocument",
    "SharedProvenance",
    "SharedSection",
    "SectionCompositionDraft",
    "SectionCompositionPlan",
    "SectionSource",
    "SectionTaskSummary",
    "SectionWriteResult",
    "SectionWriteValidationError",
    "SectionWriterDraft",
    "SectionWriterRequest",
    "TableNode",
    "TaskAnchor",
    "build_shared_lesson_document",
    "canonical_shared_lesson_payload",
    "compose_section",
    "shared_lesson_content_hash",
    "validate_and_build_composition",
    "validate_and_build_section",
    "validate_composition_plan",
    "verify_shared_lesson_source",
    "write_section",
]
